/* Label: Partition Data */
/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '4/11/25, 10:30 AM' 
 * Generated by 'boodusami' 
 * Generated on server 'ODAWS02-USW2.ODA.SAS.COM' 
 * Generated on SAS platform 'Linux LIN X64 5.14.0-284.30.1.el9_2.x86_64' 
 * Generated on SAS version '9.04.01M7P08062020' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:137.0) Gecko/20100101 Firefox/137.0' 
 * Generated on web client 'https://odamid-usw2.oda.sas.com/SASStudio/main?locale=en_US&zone=GMT-04%253A00&ticket=ST-4881-Q2an7vI0AoSkEHe5wzz9-cas' 
 *
 */



	retain __tmp1-__tmp%trim(&count) __nobs__ __nobs1__ __nobs2__;
	retain __nobs__ __seed__ _n1_;
	drop __k__;
	drop _i_ __seed__ __tmp1-__tmp%trim(&count);
	drop _n1_ __nobs__ __nobs1__ __nobs2__;
	array __tmp(*) __tmp1-__tmp%trim(&count);

	if (_n_=1) then
		do;
			__seed__=54321;
			__nobs__=&count;
		end;

	if first.Target then
		do;
			set work._meansOut_;
			by Target;

			do _i_=1 to __nobs__;
				__tmp(_i_)=_i_;
			end;

			if (__nobs__ < dim(__tmp)) then
				do;

					do _i_=__nobs__+1 to dim(__tmp);
						__tmp(_i_)=0;
					end;
				end;
			call ranperm(__seed__, of __tmp(*));

			if (__nobs__ < dim(__tmp)) then
				do;

					/* Move non-zero values to beginning of list */
					do _i_=1 to dim(__tmp);

						if (__tmp(_i_)=0) then
							do;

								if (_i_ < dim(__tmp)) then
									do;
										__k__=_i_ + 1;

										do while(__k__ < dim(__tmp) and __tmp(__k__)=0);
											__k__=__k__+1;
										end;

										if (__k__ <=dim(__tmp)) then
											do;
												__tmp(_i_)=__tmp(__k__);
												__tmp(__k__)=0;
											end;
									end;
							end;
					end;
				end;
			_n1_=0;
			__nobs1__=round(0.7*__nobs__);
			__nobs2__=round(0.3*__nobs__)+__nobs1__;
		end;
	_n1_=_n1_ + 1;

	if (_n1_ <=dim(__tmp)) then
		do;

			if (__tmp(_n1_) > 0) then
				do;

					if (__tmp(_n1_) <=__nobs1__) then
						do;
							Partition="1";
							output;
						end;
					else if (__tmp(_n1_) <=__nobs2__) then
						do;
							Partition="2";
							output;
						end;
				end;
		end;

